input: touchscreen: himax: Fix VLA usage for clang compatibility
Variable Length Arrays (VLA) are not allowed in Linux kernel since 4.20
and cause build errors with clang:
  error: variable length arrays are a C99 feature [-Werror,-Wvla-extension]

Replace VLA with dynamic memory allocation using kmalloc/kfree in:

himax_platform.c:
  - himax_bus_write(): uint8_t buf[length + 1]
  - himax_bus_master_write(): uint8_t buf[length]

himax_inspection.c:
  - mpTestFunc(): uint32_t RAW[datalen]

Signed-off-by: SonicBSV <sonicbsv@ya.ru>
Signed-off-by: rsuntk <rissu.ntk@gmail.com>