Revert "techpack: asoc: codecs: tfa9874: Force cold start on speakerboost"
* This cause tfa_dev_start to spit errno 6 (ENXIO)

[  201.666690] PrintAssert:tfaRunColdStartup (techpack/audio/asoc/codecs/tfa9874/src/tfa_dsp.c:3119) error code:6
[  201.666899] tfa98xx 6-0034: tfa_dev_start failed! (err 6) - 0
[  201.670487] Active_profile:NONE, next_profile:speaker
[  201.704376] coldboot (ACS) did not set

Speaker still works fine, but this error cause unnecessary dmesg clutter

This reverts commit 9de185f0c8b6e2131406b7adcac451bc5295be28.

Signed-off-by: ris <rissu.ntk@gmail.com>