Revert "BACKPORT: cred: add get_cred_rcu()"
* Oops, we cherry-picked it twice.

In file included from ../arch/arm64/kernel/asm-offsets.c:25:
In file included from ../include/linux/kvm_host.h:39:
In file included from ../arch/arm64/include/asm/kvm_host.h:42:
In file included from ../include/kvm/arm_pmu.h:21:
In file included from ../include/linux/perf_event.h:48:
In file included from ../include/linux/ftrace.h:14:
In file included from ../include/linux/ptrace.h:7:
In file included from ../include/linux/sched/signal.h:10:
../include/linux/cred.h:283:34: error: redefinition of 'get_cred_rcu'
  283 | static inline const struct cred *get_cred_rcu(const struct cred *cred)
      |                                  ^
../include/linux/cred.h:260:34: note: previous definition is here
  260 | static inline const struct cred *get_cred_rcu(const struct cred *cred)
      |                                  ^
  HOSTLD  scripts/dtc/dtc
1 error generated.

This reverts commit b19ca55514c425aed806831d075cef224262baa5.

Signed-off-by: rsuntk <rissu.ntk@gmail.com>